# Файл конфігурації для Docker Compose
# Використовуємо останню стабільну схему compose
name: nl2sql-application

services:
  nl2sql-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nl2sql-app
    ports:
      - "8000:8000"  # FastAPI
      - "8501:8501"  # Streamlit
    volumes:
      # Постійне зберігання даних
      - ./data:/app/data
    environment:
      # Налаштування LLM клієнта
      LLM_PROVIDER: "groq"
      GROQ_API_KEY: "${GROQ_API_KEY}"
      # Налаштування бази даних
      DATABASE_URL: "sqlite:///./data/app.db"
      APP_ENV: "production"
    restart: always
    healthcheck:
      test: curl --fail http://localhost:8000/api/v1/health || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
